services:
  db:
    image: mysql:latest
    container_name: mysql_titan_core_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD} 
      MYSQL_DATABASE: ${MYSQL_NAME} 
      MYSQL_USER: ${MYSQL_USER} 
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    networks:
      - titan_core_network

  phpmyadmin: 
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_titan_core
    restart: always
    ports:
      - "${PHPMYADMIN_PORT}:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - titan_core_network
    depends_on:
      - db

networks:
  titan_core_network:
    driver: bridge